# Site settings
title: Got Gastro
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/gastro" # the subpath of your site, e.g. /blog/
url: "http://auxesis.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor' ]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"

gmaps_api_key: "AIzaSyBxaCRguM2pvw9HOLybx5ZP6Cuo94KnJwg"
