source 'https://rubygems.org'
ruby '2.3.1'

gem 'bundler'
gem 'sinatra'
gem 'puma'
gem 'rack-google-analytics'
gem 'haml'
gem 'sequel'
gem 'sequel_mappable'
gem 'geokit'
gem 'mysql2'
gem 'sinatra-contrib'
gem 'rack-ssl'
gem 'rest-client'
gem 'activesupport'
gem 'mail'
gem 'virtus'
gem 'activemodel'
gem 'sidekiq'
gem 'foreman'
gem 'newrelic_rpm'
gem 'dotiw'
gem 'addressable'
gem 'redcarpet'
gem 'valid_email'

group :development do
  gem 'rerun'
  gem 'pry'
  gem 'mailcatcher'
  gem 'launchy'
end

group :test do
  gem 'rake'
  gem 'rspec'
  gem 'capybara'
  gem 'webmock'
  gem 'delorean'
  gem 'faker'
  gem 'poltergeist'
  gem 'database_cleaner'
end
