---
test:
  database_uri: <%= ENV["DATABASE_URL"] || ENV["DATABASE_URI"] || "mysql2://gotgastro_test:test@localhost/gotgastro_test" %>
development:
  database_uri: <%= ENV["DATABASE_URL"] || ENV["DATABASE_URI"] || 'mysql2://gotgastro_dev:dev@localhost/gotgastro_development' %>
production:
  # Leave ENV lookup in, so deploys to heroku work in parallel.
  database_uri: <%= ENV["DATABASE_URL"] || ENV["DATABASE_URI"] %>
